apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    chart: "loki"
    targetRevision: 6.8.0
    helm:
      releaseName: "loki"
      values: |-
        loki:
          schemaConfig:
            configs:
              - from: 2024-04-01
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          ingester:
            chunk_encoding: snappy
          tracing:
            enabled: true
          querier:
            max_concurrent: 4

          storage:
            type: s3
            bucketNames:
              chunks: "chunks"
              ruler: "ruler"
              admin: "admin"
            s3:
              s3: s3://NPZ29OCGUNGS8T948JSB:mfn9MubZLxAWHCuzEgSXZ6KKCtVaiQOBdgEUx9iP@ceph-object.aoldacloud.com/aolda
              endpoint: https://ceph-object.aoldacloud.com
              region: us-east-1
              secretAccessKey: mfn9MubZLxAWHCuzEgSXZ6KKCtVaiQOBdgEUx9iP
              accessKeyId: NPZ29OCGUNGS8T948JSB
              signatureVersion: v4
              s3ForcePathStyle: true
              insecure: false

        deploymentMode: SimpleScalable

        backend:
          replicas: 3
        read:
          replicas: 3
        write:
          replicas: 3

        # Disable minio storage
        minio:
          enabled: false

        # Zero out replica counts of other deployment modes
        singleBinary:
          replicas: 0

        ingester:
          replicas: 0
        querier:
          replicas: 0
        queryFrontend:
          replicas: 0
        queryScheduler:
          replicas: 0
        distributor:
          replicas: 0
        compactor:
          replicas: 0
        indexGateway:
          replicas: 0
        bloomCompactor:
          replicas: 0
        bloomGateway:
          replicas: 0
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
