apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    path: apps/loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.8.0 
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true